# Generated by Django 5.1.4 on 2025-01-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_recommender', '0002_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
