# Generated by Django 5.1.4 on 2025-01-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_recommender', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_username',
            field=models.CharField(default='default user', max_length=255),
        ),
    ]
