# Generated by Django 5.1.4 on 2025-05-03 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_recommender', '0005_review_review_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='product_recommender.product'),
        ),
    ]
