# Generated by Django 5.1.4 on 2025-05-15 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_recommender', '0006_alter_summary_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_time', models.FloatField()),
                ('reviews_time', models.FloatField()),
                ('num_reviews', models.IntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_recommender.product')),
            ],
        ),
    ]
